def cargar_datos(grafo):
    # grafo.agregar_nodo('A', 'almacen', tuple(map(float, [10, 10])))
    # grafo.agregar_nodo('B', 'punto_venta', tuple(map(float, [30, 10])))
    # grafo.agregar_nodo('C', 'punto_venta', tuple(map(float, [30, 30])))
    # grafo.agregar_nodo('D', 'punto_venta', tuple(map(float, [10, 30])))

    # grafo.agregar_arista('A', 'B', 8, 0, 0)
    # grafo.agregar_arista('A', 'C', 5, 0, 0)
    # grafo.agregar_arista('A', 'D', 10, 0, 0)
    # grafo.agregar_arista('B', 'D', 5, 0, 0)
    # grafo.agregar_arista('B', 'C', 6, 0, 0)
    # grafo.agregar_arista('C', 'D', 7, 0, 0)
    
    grafo.agregar_nodo('CarnesSelectas Ltda.', 'almacen', tuple(map(float, [0, 220])))
    grafo.agregar_nodo('La Esquina Carnívora', 'punto_venta', tuple(map(float, [85, 670])))
    grafo.agregar_nodo('CarnesDelicias Express', 'punto_venta', tuple(map(float, [295 , 400 ])))
    grafo.agregar_nodo('La Fama', 'punto_venta', tuple(map(float, [605 , 320 ])))
    grafo.agregar_nodo('Magrocarnes', 'punto_venta', tuple(map(float, [345 , 0 ])))
    grafo.agregar_nodo('DistriCarnes', 'punto_venta', tuple(map(float, [615 , 60 ])))
    grafo.agregar_nodo('Carnicería Delicatta', 'punto_venta', tuple(map(float, [370 , 740 ])))
    grafo.agregar_nodo('La macheleria', 'punto_venta', tuple(map(float, [716 , 710 ])))
    grafo.agregar_nodo('Carnex', 'punto_venta', tuple(map(float, [940 , 490 ])))
    grafo.agregar_nodo('SurtiCarnes', 'punto_venta', tuple(map(float, [825 , 270 ])))
    
    grafo.agregar_arista('CarnesSelectas Ltda.', 'CarnesDelicias Express', 60, 10, 15)
    grafo.agregar_arista('CarnesSelectas Ltda.', 'La Fama', 67, 28, 31)
    grafo.agregar_arista('CarnesSelectas Ltda.', 'Magrocarnes', 61, 10, 18)
    grafo.agregar_arista('CarnesSelectas Ltda.', 'La Esquina Carnívora', 55, 16, 20)
    grafo.agregar_arista('CarnesSelectas Ltda.', 'DistriCarnes', 89, 40, 57)
    grafo.agregar_arista('CarnesSelectas Ltda.', 'Carnicería Delicatta', 78, 35, 45)
    grafo.agregar_arista('CarnesSelectas Ltda.', 'La macheleria', 90, 42, 60)
    grafo.agregar_arista('CarnesSelectas Ltda.', 'Carnex', 72, 30, 40)
    grafo.agregar_arista('CarnesSelectas Ltda.', 'SurtiCarnes', 80, 36, 50)

    grafo.agregar_arista('La Esquina Carnívora', 'CarnesDelicias Express', 48, 12, 25)
    grafo.agregar_arista('La Esquina Carnívora', 'La Fama', 40, 8, 18)
    grafo.agregar_arista('La Esquina Carnívora', 'Magrocarnes', 44, 10, 22)
    grafo.agregar_arista('La Esquina Carnívora', 'DistriCarnes', 72, 30, 48)
    grafo.agregar_arista('La Esquina Carnívora', 'Carnicería Delicatta', 90, 38, 55)
    grafo.agregar_arista('La Esquina Carnívora', 'La macheleria', 78, 36, 45)
    grafo.agregar_arista('La Esquina Carnívora', 'Carnex', 80, 34, 40)
    grafo.agregar_arista('La Esquina Carnívora', 'SurtiCarnes', 85, 40, 52)

    grafo.agregar_arista('CarnesDelicias Express', 'La Fama', 30, 7, 15)
    grafo.agregar_arista('CarnesDelicias Express', 'Magrocarnes', 20, 5, 10)
    grafo.agregar_arista('CarnesDelicias Express', 'DistriCarnes', 50, 15, 25)
    grafo.agregar_arista('CarnesDelicias Express', 'Carnicería Delicatta', 70, 25, 40)
    grafo.agregar_arista('CarnesDelicias Express', 'La macheleria', 55, 18, 30)
    grafo.agregar_arista('CarnesDelicias Express', 'Carnex', 45, 12, 22)
    grafo.agregar_arista('CarnesDelicias Express', 'SurtiCarnes', 40, 10, 20)

    grafo.agregar_arista('La Fama', 'Magrocarnes', 12, 4, 8)
    grafo.agregar_arista('La Fama', 'DistriCarnes', 28, 10, 15)
    grafo.agregar_arista('La Fama', 'Carnicería Delicatta', 35, 15, 22)
    grafo.agregar_arista('La Fama', 'La macheleria', 25, 8, 12)
    grafo.agregar_arista('La Fama', 'Carnex', 30, 10, 18)
    grafo.agregar_arista('La Fama', 'SurtiCarnes', 20, 5, 10)
    
    grafo.agregar_arista('Magrocarnes', 'DistriCarnes', 28, 10, 15)
    grafo.agregar_arista('Magrocarnes', 'Carnicería Delicatta', 35, 15, 22)
    grafo.agregar_arista('Magrocarnes', 'La macheleria', 25, 8, 12)
    grafo.agregar_arista('Magrocarnes', 'Carnex', 30, 10, 18)
    grafo.agregar_arista('Magrocarnes', 'SurtiCarnes', 20, 5, 10)
    
    grafo.agregar_arista('DistriCarnes', 'Carnicería Delicatta', 35, 15, 22)
    grafo.agregar_arista('DistriCarnes', 'La macheleria', 25, 8, 12)
    grafo.agregar_arista('DistriCarnes', 'Carnex', 30, 10, 18)
    grafo.agregar_arista('DistriCarnes', 'SurtiCarnes', 20, 5, 10)
    
    grafo.agregar_arista('Carnicería Delicatta', 'La macheleria', 25, 8, 12)
    grafo.agregar_arista('Carnicería Delicatta', 'Carnex', 30, 10, 18)
    grafo.agregar_arista('Carnicería Delicatta', 'SurtiCarnes', 20, 5, 10)
    
    grafo.agregar_arista('La macheleria', 'Carnex', 20, 5, 10)
    grafo.agregar_arista('La macheleria', 'SurtiCarnes', 20, 5, 10)
    
    grafo.agregar_arista('Carnex', 'SurtiCarnes', 20, 5, 10)
    